version: '3.6'

services:
  frontend:
    build:
      context: ../client/sales/
      dockerfile: Dockerfile
    environment:
      BACKEND_HOST: backend
    ports:
      - 5000:5000
    command: gunicorn -w 4 flaskSales:app -b 0.0.0.0:5000
  backend:
    image: sales:latest
    ports:
      - 9090:9090
