# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sales_proto_definition.sales_pb2 as sales__pb2


class SaleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.importSales = channel.stream_unary(
            "/SaleService/importSales",
            request_serializer=sales__pb2.Sale.SerializeToString,
            response_deserializer=sales__pb2.SaleResponse.FromString,
        )
        self.getStatistics = channel.unary_unary(
            "/SaleService/getStatistics",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=sales__pb2.Statistic.FromString,
        )


class SaleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def importSales(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def getStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SaleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "importSales": grpc.stream_unary_rpc_method_handler(
            servicer.importSales,
            request_deserializer=sales__pb2.Sale.FromString,
            response_serializer=sales__pb2.SaleResponse.SerializeToString,
        ),
        "getStatistics": grpc.unary_unary_rpc_method_handler(
            servicer.getStatistics,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=sales__pb2.Statistic.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "SaleService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SaleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def importSales(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/SaleService/importSales",
            sales__pb2.Sale.SerializeToString,
            sales__pb2.SaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def getStatistics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/SaleService/getStatistics",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sales__pb2.Statistic.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
